name: Resolve Issue with OpenHands
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  resolve:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@openhands-agent') || ${{ vars.OPENHANDS_MACRO }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          
      - name: Setup Git and fix permissions
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          sudo chown -R $(whoami):$(whoami) .
          sudo chmod -R 777 .git
          sudo rm -f .git/index.lock
          
      - name: Run OpenHands
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
          LLM_MODEL: ${{ vars.LLM_MODEL || 'meta-llama/Llama-Vision-Free' }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
        run: |
          docker run --rm \
            --user root \
            -v $GITHUB_WORKSPACE:/workspace \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /workspace \
            -e LLM_API_KEY \
            -e LLM_BASE_URL \
            -e LLM_MODEL \
            -e PAT_TOKEN \
            ghcr.io/all-hands-ai/openhands:latest \
            python -m openhands.resolver.resolve_issue \
              --repo-path /workspace \
              --issue-number ${{ github.event.issue.number || github.event.pull_request.number }}